//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EK_MultipleTransporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EK_MultipleTransporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.*| Office Files|*.doc;*.docx;*.ppt| XLS files (*.xls)|*.xls| XLSX files (*.xlsx)|*.xlsx| Image Files|*.jpg;*.jpeg;*.png;*.gif;*.tif;.
        /// </summary>
        public static string AllowedTypes {
            get {
                return ResourceManager.GetString("AllowedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap apartment_icon {
            get {
                object obj = ResourceManager.GetObject("apartment_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arsa {
            get {
                object obj = ResourceManager.GetObject("arsa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error that we are avare of but will finish it later. Details are :.
        /// </summary>
        public static string AvaredErrorTypes {
            get {
                return ResourceManager.GetString("AvaredErrorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Yükleme yapmadan önce tüm zorunlu alanları için birer seçim yapınız.
        /// </summary>
        public static string ChooseAllRequiredFields {
            get {
                return ResourceManager.GetString("ChooseAllRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dökümanınızı Seçiniz....
        /// </summary>
        public static string ChooseDocument {
            get {
                return ResourceManager.GetString("ChooseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasörünüzü Seçiniz....
        /// </summary>
        public static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce Proje Türünü Seçiniz..
        /// </summary>
        public static string ChooseProjectType {
            get {
                return ResourceManager.GetString("ChooseProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distributor {
            get {
                object obj = ResourceManager.GetObject("distributor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doküman Türü.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading from OTCS db error..
        /// </summary>
        public static string ErrorTypeDbTransacts {
            get {
                return ResourceManager.GetString("ErrorTypeDbTransacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaultException has been thrown. Web services will not return any answer for a while. Program is stopping itself for this period. Please do not do anything..
        /// </summary>
        public static string ErrorTypeFaultException {
            get {
                return ResourceManager.GetString("ErrorTypeFaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumanlar yüklenirken bir hata oluştu. Detaylar için back-up dosyanıza bakınız..
        /// </summary>
        public static string ErrorTypeProccessing {
            get {
                return ResourceManager.GetString("ErrorTypeProccessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAP Exception has been thrown. Web services will not return any answer for a while. Program is stopping itself for this period. Please do not do anything..
        /// </summary>
        public static string ErrorTypeSOAPException {
            get {
                return ResourceManager.GetString("ErrorTypeSOAPException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş alanlarını filtreleyin....
        /// </summary>
        public static string filterText {
            get {
                return ResourceManager.GetString("filterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞIMSIZ BÖLÜM.
        /// </summary>
        public static string IndependentWorkSpace {
            get {
                return ResourceManager.GetString("IndependentWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap law {
            get {
                object obj = ResourceManager.GetObject("law", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node derinliği beklenen değerin üzerinde. Lütfen bu işlemi gerçekleştiremediğinizi yüklenici firmaya bildiriniz..
        /// </summary>
        public static string NodeDeepnessExceed {
            get {
                return ResourceManager.GetString("NodeDeepnessExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap personel {
            get {
                object obj = ResourceManager.GetObject("personel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlandı....
        /// </summary>
        public static string ProcessIsDone {
            get {
                return ResourceManager.GetString("ProcessIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlanamadı....
        /// </summary>
        public static string ProcessIsNotDone {
            get {
                return ResourceManager.GetString("ProcessIsNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeyrek.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili alan sayısı   :.
        /// </summary>
        public static string SelectedItemNumber {
            get {
                return ResourceManager.GetString("SelectedItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Yüklenecek klasörü ve Hedef dizini seçiniz..
        /// </summary>
        public static string WarnMessageChooseTargets {
            get {
                return ResourceManager.GetString("WarnMessageChooseTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Servis şu an çalışmıyor!.
        /// </summary>
        public static string WebServicesNotWorking {
            get {
                return ResourceManager.GetString("WebServicesNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeler doldurulurken bir hata oluştu.
        /// </summary>
        public static string WorkerMethodException {
            get {
                return ResourceManager.GetString("WorkerMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
